[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink-contracts/",
    "@teleporter/=lib/teleporter/"
]

# Compiler settings
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# Network settings
[rpc_endpoints]
fuji = "${AVALANCHE_FUJI_RPC}"
avalanche = "${AVALANCHE_MAINNET_RPC}"
localhost = "http://localhost:8545"

# Etherscan API configuration for verification - uncomment for contract verification
# [etherscan]
# fuji = { key = "${SNOWTRACE_API_KEY}", url = "https://api-testnet.snowtrace.io/api" }
# avalanche = { key = "${SNOWTRACE_API_KEY}", url = "https://api.snowtrace.io/api" }

# Testing
[fuzz]
runs = 256
max_test_rejects = 65536
seed = "0x3e8"
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 128
fail_on_revert = false